[2023-01-31T19:06:19.955] [ERROR] myLoggerError - PID MASTER= 26264
[2023-01-31T19:14:33.439] [ERROR] myLoggerError - PID MASTER= 4056
[2023-01-31T19:14:54.253] [ERROR] myLoggerError - PID MASTER= 3336
[2023-01-31T19:15:03.931] [ERROR] myLoggerError - PID MASTER= 14476
[2023-01-31T19:15:08.462] [ERROR] myLoggerError - PID MASTER= 28472
[2023-01-31T19:18:44.056] [ERROR] myLoggerError - PID MASTER= 7996
[2023-01-31T20:04:24.264] [ERROR] myLoggerError - PID MASTER= 18548
[2023-01-31T20:07:10.019] [ERROR] myLoggerError - Error: self signed certificate in certificate chain
    at TLSSocket.onConnectSecure (node:_tls_wrap:1530:34)
    at TLSSocket.emit (node:events:520:28)
    at TLSSocket._finishInit (node:_tls_wrap:944:8)
    at TLSWrap.ssl.onhandshakedone (node:_tls_wrap:725:12) {
  code: 'ESOCKET',
  command: 'CONN'
}
[2023-01-31T20:09:48.558] [ERROR] myLoggerError - PID MASTER= 16176
[2023-01-31T20:10:07.324] [ERROR] myLoggerError - Error: self signed certificate in certificate chain
    at TLSSocket.onConnectSecure (node:_tls_wrap:1530:34)
    at TLSSocket.emit (node:events:520:28)
    at TLSSocket._finishInit (node:_tls_wrap:944:8)
    at TLSWrap.ssl.onhandshakedone (node:_tls_wrap:725:12) {
  code: 'ESOCKET',
  command: 'CONN'
}
[2023-01-31T20:11:39.903] [ERROR] myLoggerError - PID MASTER= 21064
[2023-01-31T20:11:43.061] [ERROR] myLoggerError - PID MASTER= 22500
[2023-01-31T20:12:06.582] [ERROR] myLoggerError - Error: self signed certificate in certificate chain
    at TLSSocket.onConnectSecure (node:_tls_wrap:1530:34)
    at TLSSocket.emit (node:events:520:28)
    at TLSSocket._finishInit (node:_tls_wrap:944:8)
    at TLSWrap.ssl.onhandshakedone (node:_tls_wrap:725:12) {
  code: 'ESOCKET',
  command: 'CONN'
}
[2023-01-31T20:13:29.409] [ERROR] myLoggerError - PID MASTER= 18120
[2023-01-31T20:13:50.784] [ERROR] myLoggerError - Error: self signed certificate in certificate chain
    at TLSSocket.onConnectSecure (node:_tls_wrap:1530:34)
    at TLSSocket.emit (node:events:520:28)
    at TLSSocket._finishInit (node:_tls_wrap:944:8)
    at TLSWrap.ssl.onhandshakedone (node:_tls_wrap:725:12) {
  code: 'ESOCKET',
  command: 'CONN'
}
[2023-01-31T20:15:13.957] [ERROR] myLoggerError - PID MASTER= 7720
[2023-01-31T20:15:36.616] [ERROR] myLoggerError - PID MASTER= 32816
[2023-01-31T20:16:00.590] [ERROR] myLoggerError - PID MASTER= 35472
[2023-01-31T20:18:33.205] [ERROR] myLoggerError - PID MASTER= 4300
[2023-01-31T20:19:54.602] [ERROR] myLoggerError - Error: self signed certificate in certificate chain
    at TLSSocket.onConnectSecure (node:_tls_wrap:1530:34)
    at TLSSocket.emit (node:events:520:28)
    at TLSSocket._finishInit (node:_tls_wrap:944:8)
    at TLSWrap.ssl.onhandshakedone (node:_tls_wrap:725:12) {
  code: 'ESOCKET',
  command: 'CONN'
}
[2023-01-31T20:23:03.612] [ERROR] myLoggerError - PID MASTER= 18548
[2023-01-31T20:50:48.003] [ERROR] myLoggerError - PID MASTER= 27076
[2023-01-31T20:51:12.852] [ERROR] myLoggerError - PID MASTER= 30876
[2023-01-31T20:52:21.637] [ERROR] myLoggerError - PID MASTER= 35780
[2023-01-31T20:53:12.900] [ERROR] myLoggerError - PID MASTER= 3708
[2023-01-31T20:55:57.475] [ERROR] myLoggerError - PID MASTER= 9064
[2023-01-31T20:57:22.678] [ERROR] myLoggerError - PID MASTER= 28376
[2023-01-31T21:05:13.583] [ERROR] myLoggerError - PID MASTER= 2128
[2023-01-31T21:06:13.179] [ERROR] myLoggerError - PID MASTER= 32552
[2023-01-31T21:06:33.962] [ERROR] myLoggerError - PID MASTER= 8456
[2023-01-31T21:06:59.248] [ERROR] myLoggerError - PID MASTER= 18152
[2023-01-31T21:07:52.528] [ERROR] myLoggerError - PID MASTER= 25580
[2023-01-31T21:08:30.783] [ERROR] myLoggerError - PID MASTER= 27244
[2023-01-31T21:09:58.031] [ERROR] myLoggerError - PID MASTER= 35680
[2023-01-31T21:12:17.870] [ERROR] myLoggerError - PID MASTER= 24856
[2023-01-31T21:13:17.433] [ERROR] myLoggerError - PID MASTER= 19600
[2023-01-31T21:13:57.026] [ERROR] myLoggerError - PID MASTER= 35436
[2023-01-31T21:14:25.627] [ERROR] myLoggerError - PID MASTER= 26012
[2023-01-31T21:14:31.544] [ERROR] myLoggerError - PID MASTER= 27780
[2023-01-31T21:14:38.040] [ERROR] myLoggerError - PID MASTER= 35124
[2023-01-31T21:16:12.325] [ERROR] myLoggerError - PID MASTER= 29544
[2023-01-31T21:21:52.244] [ERROR] myLoggerError - PID MASTER= 1884
[2023-01-31T21:25:37.228] [ERROR] myLoggerError - PID MASTER= 25104
[2023-01-31T21:29:39.418] [ERROR] myLoggerError - PID MASTER= 21976
[2023-01-31T21:30:04.076] [ERROR] myLoggerError - PID MASTER= 14548
[2023-01-31T21:30:15.445] [ERROR] myLoggerError - PID MASTER= 16720
[2023-01-31T21:31:55.960] [ERROR] myLoggerError - PID MASTER= 11112
[2023-01-31T21:32:08.007] [ERROR] myLoggerError - PID MASTER= 17916
[2023-01-31T21:35:26.202] [ERROR] myLoggerError - PID MASTER= 28912
[2023-01-31T21:55:12.563] [ERROR] myLoggerError - PID MASTER= 29708
[2023-01-31T22:05:29.838] [ERROR] myLoggerError - PID MASTER= 13804
[2023-01-31T22:09:33.983] [ERROR] myLoggerError - PID MASTER= 952
[2023-01-31T22:16:54.019] [ERROR] myLoggerError - PID MASTER= 11856
[2023-01-31T22:26:55.998] [ERROR] myLoggerError - PID MASTER= 31660
[2023-01-31T22:30:14.646] [ERROR] myLoggerError - PID MASTER= 35456
[2023-01-31T22:32:37.964] [ERROR] myLoggerError - PID MASTER= 14800
[2023-01-31T22:34:06.353] [ERROR] myLoggerError - PID MASTER= 19656
[2023-01-31T22:38:47.744] [ERROR] myLoggerError - PID MASTER= 27024
[2023-01-31T22:39:16.722] [ERROR] myLoggerError - PID MASTER= 24940
[2023-01-31T22:42:27.702] [ERROR] myLoggerError - PID MASTER= 22980
[2023-01-31T22:45:53.312] [ERROR] myLoggerError - PID MASTER= 18968
[2023-01-31T22:47:17.315] [ERROR] myLoggerError - PID MASTER= 35692
[2023-01-31T22:48:31.590] [ERROR] myLoggerError - PID MASTER= 26848
[2023-01-31T22:49:09.225] [ERROR] myLoggerError - PID MASTER= 26356
[2023-01-31T22:50:43.767] [ERROR] myLoggerError - PID MASTER= 35136
[2023-01-31T22:54:35.329] [ERROR] myLoggerError - PID MASTER= 33292
[2023-01-31T22:55:33.214] [ERROR] myLoggerError - PID MASTER= 25032
[2023-01-31T22:59:15.894] [ERROR] myLoggerError - PID MASTER= 35460
[2023-01-31T23:00:10.038] [ERROR] myLoggerError - PID MASTER= 28104
[2023-01-31T23:04:59.944] [ERROR] myLoggerError - PID MASTER= 15936
[2023-01-31T23:08:10.133] [ERROR] myLoggerError - PID MASTER= 35412
[2023-01-31T23:08:27.243] [ERROR] myLoggerError - PID MASTER= 25780
[2023-01-31T23:08:48.925] [ERROR] myLoggerError - PID MASTER= 18852
[2023-01-31T23:09:05.182] [ERROR] myLoggerError - PID MASTER= 33132
[2023-01-31T23:09:13.242] [ERROR] myLoggerError - PID MASTER= 26012
[2023-01-31T23:12:42.902] [ERROR] myLoggerError - PID MASTER= 17308
[2023-01-31T23:13:22.271] [ERROR] myLoggerError - PID MASTER= 31352
[2023-02-01T00:01:58.206] [ERROR] myLoggerError - PID MASTER= 8432
[2023-02-01T00:06:31.336] [ERROR] myLoggerError - PID MASTER= 31324
[2023-02-01T00:11:42.379] [ERROR] myLoggerError - PID MASTER= 19320
[2023-02-01T00:15:05.655] [ERROR] myLoggerError - PID MASTER= 15560
[2023-02-01T11:28:16.323] [ERROR] myLoggerError - PID MASTER= 30608
[2023-02-01T11:28:20.886] [ERROR] myLoggerError - Catch de error en servidor! Error: bind EADDRINUSE null:8080
    at listenOnPrimaryHandle (node:net:1397:18)
    at shared (node:internal/cluster/child:149:3)
    at Worker.<anonymous> (node:internal/cluster/child:106:7)
    at process.onInternalMessage (node:internal/cluster/utils:49:5)
    at process.emit (node:events:532:35)
    at emit (node:internal/child_process:938:14)
    at processTicksAndRejections (node:internal/process/task_queues:84:21) {
  errno: -4091,
  code: 'EADDRINUSE',
  syscall: 'bind',
  address: null,
  port: 8080
}
[2023-02-01T11:28:20.892] [ERROR] myLoggerError - Catch de error en servidor! Error: bind EADDRINUSE null:8080
    at listenOnPrimaryHandle (node:net:1397:18)
    at shared (node:internal/cluster/child:149:3)
    at Worker.<anonymous> (node:internal/cluster/child:106:7)
    at process.onInternalMessage (node:internal/cluster/utils:49:5)
    at process.emit (node:events:532:35)
    at emit (node:internal/child_process:938:14)
    at processTicksAndRejections (node:internal/process/task_queues:84:21) {
  errno: -4091,
  code: 'EADDRINUSE',
  syscall: 'bind',
  address: null,
  port: 8080
}
[2023-02-01T11:28:20.994] [ERROR] myLoggerError - Catch de error en servidor! Error: bind EADDRINUSE null:8080
    at listenOnPrimaryHandle (node:net:1397:18)
    at shared (node:internal/cluster/child:149:3)
    at Worker.<anonymous> (node:internal/cluster/child:106:7)
    at process.onInternalMessage (node:internal/cluster/utils:49:5)
    at process.emit (node:events:532:35)
    at emit (node:internal/child_process:938:14)
    at processTicksAndRejections (node:internal/process/task_queues:84:21) {
  errno: -4091,
  code: 'EADDRINUSE',
  syscall: 'bind',
  address: null,
  port: 8080
}
[2023-02-01T11:28:21.197] [ERROR] myLoggerError - Catch de error en servidor! Error: bind EADDRINUSE null:8080
    at listenOnPrimaryHandle (node:net:1397:18)
    at shared (node:internal/cluster/child:149:3)
    at Worker.<anonymous> (node:internal/cluster/child:106:7)
    at process.onInternalMessage (node:internal/cluster/utils:49:5)
    at process.emit (node:events:532:35)
    at emit (node:internal/child_process:938:14)
    at processTicksAndRejections (node:internal/process/task_queues:84:21) {
  errno: -4091,
  code: 'EADDRINUSE',
  syscall: 'bind',
  address: null,
  port: 8080
}
[2023-02-01T11:28:21.199] [ERROR] myLoggerError - Catch de error en servidor! Error: bind EADDRINUSE null:8080
    at listenOnPrimaryHandle (node:net:1397:18)
    at shared (node:internal/cluster/child:149:3)
    at Worker.<anonymous> (node:internal/cluster/child:106:7)
    at process.onInternalMessage (node:internal/cluster/utils:49:5)
    at process.emit (node:events:532:35)
    at emit (node:internal/child_process:938:14)
    at processTicksAndRejections (node:internal/process/task_queues:84:21) {
  errno: -4091,
  code: 'EADDRINUSE',
  syscall: 'bind',
  address: null,
  port: 8080
}
[2023-02-01T11:28:21.199] [ERROR] myLoggerError - Catch de error en servidor! Error: bind EADDRINUSE null:8080
    at listenOnPrimaryHandle (node:net:1397:18)
    at shared (node:internal/cluster/child:149:3)
    at Worker.<anonymous> (node:internal/cluster/child:106:7)
    at process.onInternalMessage (node:internal/cluster/utils:49:5)
    at process.emit (node:events:532:35)
    at emit (node:internal/child_process:938:14)
    at processTicksAndRejections (node:internal/process/task_queues:84:21) {
  errno: -4091,
  code: 'EADDRINUSE',
  syscall: 'bind',
  address: null,
  port: 8080
}
[2023-02-01T11:28:21.335] [ERROR] myLoggerError - Catch de error en servidor! Error: bind EADDRINUSE null:8080
    at listenOnPrimaryHandle (node:net:1397:18)
    at shared (node:internal/cluster/child:149:3)
    at Worker.<anonymous> (node:internal/cluster/child:106:7)
    at process.onInternalMessage (node:internal/cluster/utils:49:5)
    at process.emit (node:events:532:35)
    at emit (node:internal/child_process:938:14)
    at processTicksAndRejections (node:internal/process/task_queues:84:21) {
  errno: -4091,
  code: 'EADDRINUSE',
  syscall: 'bind',
  address: null,
  port: 8080
}
[2023-02-01T11:28:21.335] [ERROR] myLoggerError - Catch de error en servidor! Error: bind EADDRINUSE null:8080
    at listenOnPrimaryHandle (node:net:1397:18)
    at shared (node:internal/cluster/child:149:3)
    at Worker.<anonymous> (node:internal/cluster/child:106:7)
    at process.onInternalMessage (node:internal/cluster/utils:49:5)
    at process.emit (node:events:532:35)
    at emit (node:internal/child_process:938:14)
    at processTicksAndRejections (node:internal/process/task_queues:84:21) {
  errno: -4091,
  code: 'EADDRINUSE',
  syscall: 'bind',
  address: null,
  port: 8080
}
[2023-02-01T11:28:21.502] [ERROR] myLoggerError - Catch de error en servidor! Error: bind EADDRINUSE null:8080
    at listenOnPrimaryHandle (node:net:1397:18)
    at shared (node:internal/cluster/child:149:3)
    at Worker.<anonymous> (node:internal/cluster/child:106:7)
    at process.onInternalMessage (node:internal/cluster/utils:49:5)
    at process.emit (node:events:532:35)
    at emit (node:internal/child_process:938:14)
    at processTicksAndRejections (node:internal/process/task_queues:84:21) {
  errno: -4091,
  code: 'EADDRINUSE',
  syscall: 'bind',
  address: null,
  port: 8080
}
[2023-02-01T11:28:21.520] [ERROR] myLoggerError - Catch de error en servidor! Error: bind EADDRINUSE null:8080
    at listenOnPrimaryHandle (node:net:1397:18)
    at shared (node:internal/cluster/child:149:3)
    at Worker.<anonymous> (node:internal/cluster/child:106:7)
    at process.onInternalMessage (node:internal/cluster/utils:49:5)
    at process.emit (node:events:532:35)
    at emit (node:internal/child_process:938:14)
    at processTicksAndRejections (node:internal/process/task_queues:84:21) {
  errno: -4091,
  code: 'EADDRINUSE',
  syscall: 'bind',
  address: null,
  port: 8080
}
[2023-02-01T11:28:21.541] [ERROR] myLoggerError - Catch de error en servidor! Error: bind EADDRINUSE null:8080
    at listenOnPrimaryHandle (node:net:1397:18)
    at shared (node:internal/cluster/child:149:3)
    at Worker.<anonymous> (node:internal/cluster/child:106:7)
    at process.onInternalMessage (node:internal/cluster/utils:49:5)
    at process.emit (node:events:532:35)
    at emit (node:internal/child_process:938:14)
    at processTicksAndRejections (node:internal/process/task_queues:84:21) {
  errno: -4091,
  code: 'EADDRINUSE',
  syscall: 'bind',
  address: null,
  port: 8080
}
[2023-02-01T11:28:21.542] [ERROR] myLoggerError - Catch de error en servidor! Error: bind EADDRINUSE null:8080
    at listenOnPrimaryHandle (node:net:1397:18)
    at shared (node:internal/cluster/child:149:3)
    at Worker.<anonymous> (node:internal/cluster/child:106:7)
    at process.onInternalMessage (node:internal/cluster/utils:49:5)
    at process.emit (node:events:532:35)
    at emit (node:internal/child_process:938:14)
    at processTicksAndRejections (node:internal/process/task_queues:84:21) {
  errno: -4091,
  code: 'EADDRINUSE',
  syscall: 'bind',
  address: null,
  port: 8080
}
[2023-02-01T11:28:21.707] [ERROR] myLoggerError - Catch de error en servidor! Error: bind EADDRINUSE null:8080
    at listenOnPrimaryHandle (node:net:1397:18)
    at shared (node:internal/cluster/child:149:3)
    at Worker.<anonymous> (node:internal/cluster/child:106:7)
    at process.onInternalMessage (node:internal/cluster/utils:49:5)
    at process.emit (node:events:532:35)
    at emit (node:internal/child_process:938:14)
    at processTicksAndRejections (node:internal/process/task_queues:84:21) {
  errno: -4091,
  code: 'EADDRINUSE',
  syscall: 'bind',
  address: null,
  port: 8080
}
[2023-02-01T11:28:21.710] [ERROR] myLoggerError - Catch de error en servidor! Error: bind EADDRINUSE null:8080
    at listenOnPrimaryHandle (node:net:1397:18)
    at shared (node:internal/cluster/child:149:3)
    at Worker.<anonymous> (node:internal/cluster/child:106:7)
    at process.onInternalMessage (node:internal/cluster/utils:49:5)
    at process.emit (node:events:532:35)
    at emit (node:internal/child_process:938:14)
    at processTicksAndRejections (node:internal/process/task_queues:84:21) {
  errno: -4091,
  code: 'EADDRINUSE',
  syscall: 'bind',
  address: null,
  port: 8080
}
[2023-02-01T11:28:26.671] [ERROR] myLoggerError - Catch de error en servidor! Error: bind EADDRINUSE null:8080
    at listenOnPrimaryHandle (node:net:1397:18)
    at shared (node:internal/cluster/child:149:3)
    at Worker.<anonymous> (node:internal/cluster/child:106:7)
    at process.onInternalMessage (node:internal/cluster/utils:49:5)
    at process.emit (node:events:532:35)
    at emit (node:internal/child_process:938:14)
    at processTicksAndRejections (node:internal/process/task_queues:84:21) {
  errno: -4091,
  code: 'EADDRINUSE',
  syscall: 'bind',
  address: null,
  port: 8080
}
[2023-02-01T11:28:26.676] [ERROR] myLoggerError - Catch de error en servidor! Error: bind EADDRINUSE null:8080
    at listenOnPrimaryHandle (node:net:1397:18)
    at shared (node:internal/cluster/child:149:3)
    at Worker.<anonymous> (node:internal/cluster/child:106:7)
    at process.onInternalMessage (node:internal/cluster/utils:49:5)
    at process.emit (node:events:532:35)
    at emit (node:internal/child_process:938:14)
    at processTicksAndRejections (node:internal/process/task_queues:84:21) {
  errno: -4091,
  code: 'EADDRINUSE',
  syscall: 'bind',
  address: null,
  port: 8080
}
[2023-02-01T11:28:26.717] [ERROR] myLoggerError - Catch de error en servidor! Error: bind EADDRINUSE null:8080
    at listenOnPrimaryHandle (node:net:1397:18)
    at shared (node:internal/cluster/child:149:3)
    at Worker.<anonymous> (node:internal/cluster/child:106:7)
    at process.onInternalMessage (node:internal/cluster/utils:49:5)
    at process.emit (node:events:532:35)
    at emit (node:internal/child_process:938:14)
    at processTicksAndRejections (node:internal/process/task_queues:84:21) {
  errno: -4091,
  code: 'EADDRINUSE',
  syscall: 'bind',
  address: null,
  port: 8080
}
[2023-02-01T11:28:26.727] [ERROR] myLoggerError - Catch de error en servidor! Error: bind EADDRINUSE null:8080
    at listenOnPrimaryHandle (node:net:1397:18)
    at shared (node:internal/cluster/child:149:3)
    at Worker.<anonymous> (node:internal/cluster/child:106:7)
    at process.onInternalMessage (node:internal/cluster/utils:49:5)
    at process.emit (node:events:532:35)
    at emit (node:internal/child_process:938:14)
    at processTicksAndRejections (node:internal/process/task_queues:84:21) {
  errno: -4091,
  code: 'EADDRINUSE',
  syscall: 'bind',
  address: null,
  port: 8080
}
[2023-02-01T11:28:26.737] [ERROR] myLoggerError - Catch de error en servidor! Error: bind EADDRINUSE null:8080
    at listenOnPrimaryHandle (node:net:1397:18)
    at shared (node:internal/cluster/child:149:3)
    at Worker.<anonymous> (node:internal/cluster/child:106:7)
    at process.onInternalMessage (node:internal/cluster/utils:49:5)
    at process.emit (node:events:532:35)
    at emit (node:internal/child_process:938:14)
    at processTicksAndRejections (node:internal/process/task_queues:84:21) {
  errno: -4091,
  code: 'EADDRINUSE',
  syscall: 'bind',
  address: null,
  port: 8080
}
[2023-02-01T11:28:26.741] [ERROR] myLoggerError - Catch de error en servidor! Error: bind EADDRINUSE null:8080
    at listenOnPrimaryHandle (node:net:1397:18)
    at shared (node:internal/cluster/child:149:3)
    at Worker.<anonymous> (node:internal/cluster/child:106:7)
    at process.onInternalMessage (node:internal/cluster/utils:49:5)
    at process.emit (node:events:532:35)
    at emit (node:internal/child_process:938:14)
    at processTicksAndRejections (node:internal/process/task_queues:84:21) {
  errno: -4091,
  code: 'EADDRINUSE',
  syscall: 'bind',
  address: null,
  port: 8080
}
[2023-02-01T11:31:42.603] [ERROR] myLoggerError - PID MASTER= 18844
[2023-02-01T11:31:47.246] [ERROR] myLoggerError - Catch de error en servidor! Error: bind EADDRINUSE null:8080
    at listenOnPrimaryHandle (node:net:1397:18)
    at shared (node:internal/cluster/child:149:3)
    at Worker.<anonymous> (node:internal/cluster/child:106:7)
    at process.onInternalMessage (node:internal/cluster/utils:49:5)
    at process.emit (node:events:532:35)
    at emit (node:internal/child_process:938:14)
    at processTicksAndRejections (node:internal/process/task_queues:84:21) {
  errno: -4091,
  code: 'EADDRINUSE',
  syscall: 'bind',
  address: null,
  port: 8080
}
[2023-02-01T11:31:47.252] [ERROR] myLoggerError - Catch de error en servidor! Error: bind EADDRINUSE null:8080
    at listenOnPrimaryHandle (node:net:1397:18)
    at shared (node:internal/cluster/child:149:3)
    at Worker.<anonymous> (node:internal/cluster/child:106:7)
    at process.onInternalMessage (node:internal/cluster/utils:49:5)
    at process.emit (node:events:532:35)
    at emit (node:internal/child_process:938:14)
    at processTicksAndRejections (node:internal/process/task_queues:84:21) {
  errno: -4091,
  code: 'EADDRINUSE',
  syscall: 'bind',
  address: null,
  port: 8080
}
[2023-02-01T11:31:47.357] [ERROR] myLoggerError - Catch de error en servidor! Error: bind EADDRINUSE null:8080
    at listenOnPrimaryHandle (node:net:1397:18)
    at shared (node:internal/cluster/child:149:3)
    at Worker.<anonymous> (node:internal/cluster/child:106:7)
    at process.onInternalMessage (node:internal/cluster/utils:49:5)
    at process.emit (node:events:532:35)
    at emit (node:internal/child_process:938:14)
    at processTicksAndRejections (node:internal/process/task_queues:84:21) {
  errno: -4091,
  code: 'EADDRINUSE',
  syscall: 'bind',
  address: null,
  port: 8080
}
[2023-02-01T11:31:47.387] [ERROR] myLoggerError - Catch de error en servidor! Error: bind EADDRINUSE null:8080
    at listenOnPrimaryHandle (node:net:1397:18)
    at shared (node:internal/cluster/child:149:3)
    at Worker.<anonymous> (node:internal/cluster/child:106:7)
    at process.onInternalMessage (node:internal/cluster/utils:49:5)
    at process.emit (node:events:532:35)
    at emit (node:internal/child_process:938:14)
    at processTicksAndRejections (node:internal/process/task_queues:84:21) {
  errno: -4091,
  code: 'EADDRINUSE',
  syscall: 'bind',
  address: null,
  port: 8080
}
[2023-02-01T11:31:47.597] [ERROR] myLoggerError - Catch de error en servidor! Error: bind EADDRINUSE null:8080
    at listenOnPrimaryHandle (node:net:1397:18)
    at shared (node:internal/cluster/child:149:3)
    at Worker.<anonymous> (node:internal/cluster/child:106:7)
    at process.onInternalMessage (node:internal/cluster/utils:49:5)
    at process.emit (node:events:532:35)
    at emit (node:internal/child_process:938:14)
    at processTicksAndRejections (node:internal/process/task_queues:84:21) {
  errno: -4091,
  code: 'EADDRINUSE',
  syscall: 'bind',
  address: null,
  port: 8080
}
[2023-02-01T11:31:47.625] [ERROR] myLoggerError - Catch de error en servidor! Error: bind EADDRINUSE null:8080
    at listenOnPrimaryHandle (node:net:1397:18)
    at shared (node:internal/cluster/child:149:3)
    at Worker.<anonymous> (node:internal/cluster/child:106:7)
    at process.onInternalMessage (node:internal/cluster/utils:49:5)
    at process.emit (node:events:532:35)
    at emit (node:internal/child_process:938:14)
    at processTicksAndRejections (node:internal/process/task_queues:84:21) {
  errno: -4091,
  code: 'EADDRINUSE',
  syscall: 'bind',
  address: null,
  port: 8080
}
[2023-02-01T11:31:47.894] [ERROR] myLoggerError - Catch de error en servidor! Error: bind EADDRINUSE null:8080
    at listenOnPrimaryHandle (node:net:1397:18)
    at shared (node:internal/cluster/child:149:3)
    at Worker.<anonymous> (node:internal/cluster/child:106:7)
    at process.onInternalMessage (node:internal/cluster/utils:49:5)
    at process.emit (node:events:532:35)
    at emit (node:internal/child_process:938:14)
    at processTicksAndRejections (node:internal/process/task_queues:84:21) {
  errno: -4091,
  code: 'EADDRINUSE',
  syscall: 'bind',
  address: null,
  port: 8080
}
[2023-02-01T11:31:47.905] [ERROR] myLoggerError - Catch de error en servidor! Error: bind EADDRINUSE null:8080
    at listenOnPrimaryHandle (node:net:1397:18)
    at shared (node:internal/cluster/child:149:3)
    at Worker.<anonymous> (node:internal/cluster/child:106:7)
    at process.onInternalMessage (node:internal/cluster/utils:49:5)
    at process.emit (node:events:532:35)
    at emit (node:internal/child_process:938:14)
    at processTicksAndRejections (node:internal/process/task_queues:84:21) {
  errno: -4091,
  code: 'EADDRINUSE',
  syscall: 'bind',
  address: null,
  port: 8080
}
[2023-02-01T11:31:52.600] [ERROR] myLoggerError - Catch de error en servidor! Error: bind EADDRINUSE null:8080
    at listenOnPrimaryHandle (node:net:1397:18)
    at shared (node:internal/cluster/child:149:3)
    at Worker.<anonymous> (node:internal/cluster/child:106:7)
    at process.onInternalMessage (node:internal/cluster/utils:49:5)
    at process.emit (node:events:532:35)
    at emit (node:internal/child_process:938:14)
    at processTicksAndRejections (node:internal/process/task_queues:84:21) {
  errno: -4091,
  code: 'EADDRINUSE',
  syscall: 'bind',
  address: null,
  port: 8080
}
[2023-02-01T11:31:52.645] [ERROR] myLoggerError - Catch de error en servidor! Error: bind EADDRINUSE null:8080
    at listenOnPrimaryHandle (node:net:1397:18)
    at shared (node:internal/cluster/child:149:3)
    at Worker.<anonymous> (node:internal/cluster/child:106:7)
    at process.onInternalMessage (node:internal/cluster/utils:49:5)
    at process.emit (node:events:532:35)
    at emit (node:internal/child_process:938:14)
    at processTicksAndRejections (node:internal/process/task_queues:84:21) {
  errno: -4091,
  code: 'EADDRINUSE',
  syscall: 'bind',
  address: null,
  port: 8080
}
[2023-02-01T11:31:52.810] [ERROR] myLoggerError - Catch de error en servidor! Error: bind EADDRINUSE null:8080
    at listenOnPrimaryHandle (node:net:1397:18)
    at shared (node:internal/cluster/child:149:3)
    at Worker.<anonymous> (node:internal/cluster/child:106:7)
    at process.onInternalMessage (node:internal/cluster/utils:49:5)
    at process.emit (node:events:532:35)
    at emit (node:internal/child_process:938:14)
    at processTicksAndRejections (node:internal/process/task_queues:84:21) {
  errno: -4091,
  code: 'EADDRINUSE',
  syscall: 'bind',
  address: null,
  port: 8080
}
[2023-02-01T11:31:52.812] [ERROR] myLoggerError - Catch de error en servidor! Error: bind EADDRINUSE null:8080
    at listenOnPrimaryHandle (node:net:1397:18)
    at shared (node:internal/cluster/child:149:3)
    at Worker.<anonymous> (node:internal/cluster/child:106:7)
    at process.onInternalMessage (node:internal/cluster/utils:49:5)
    at process.emit (node:events:532:35)
    at emit (node:internal/child_process:938:14)
    at processTicksAndRejections (node:internal/process/task_queues:84:21) {
  errno: -4091,
  code: 'EADDRINUSE',
  syscall: 'bind',
  address: null,
  port: 8080
}
[2023-02-01T11:31:52.909] [ERROR] myLoggerError - Catch de error en servidor! Error: bind EADDRINUSE null:8080
    at listenOnPrimaryHandle (node:net:1397:18)
    at shared (node:internal/cluster/child:149:3)
    at Worker.<anonymous> (node:internal/cluster/child:106:7)
    at process.onInternalMessage (node:internal/cluster/utils:49:5)
    at process.emit (node:events:532:35)
    at emit (node:internal/child_process:938:14)
    at processTicksAndRejections (node:internal/process/task_queues:84:21) {
  errno: -4091,
  code: 'EADDRINUSE',
  syscall: 'bind',
  address: null,
  port: 8080
}
[2023-02-01T11:31:52.910] [ERROR] myLoggerError - Catch de error en servidor! Error: bind EADDRINUSE null:8080
    at listenOnPrimaryHandle (node:net:1397:18)
    at shared (node:internal/cluster/child:149:3)
    at Worker.<anonymous> (node:internal/cluster/child:106:7)
    at process.onInternalMessage (node:internal/cluster/utils:49:5)
    at process.emit (node:events:532:35)
    at emit (node:internal/child_process:938:14)
    at processTicksAndRejections (node:internal/process/task_queues:84:21) {
  errno: -4091,
  code: 'EADDRINUSE',
  syscall: 'bind',
  address: null,
  port: 8080
}
[2023-02-01T11:31:52.918] [ERROR] myLoggerError - Catch de error en servidor! Error: bind EADDRINUSE null:8080
    at listenOnPrimaryHandle (node:net:1397:18)
    at shared (node:internal/cluster/child:149:3)
    at Worker.<anonymous> (node:internal/cluster/child:106:7)
    at process.onInternalMessage (node:internal/cluster/utils:49:5)
    at process.emit (node:events:532:35)
    at emit (node:internal/child_process:938:14)
    at processTicksAndRejections (node:internal/process/task_queues:84:21) {
  errno: -4091,
  code: 'EADDRINUSE',
  syscall: 'bind',
  address: null,
  port: 8080
}
[2023-02-01T11:31:52.959] [ERROR] myLoggerError - Catch de error en servidor! Error: bind EADDRINUSE null:8080
    at listenOnPrimaryHandle (node:net:1397:18)
    at shared (node:internal/cluster/child:149:3)
    at Worker.<anonymous> (node:internal/cluster/child:106:7)
    at process.onInternalMessage (node:internal/cluster/utils:49:5)
    at process.emit (node:events:532:35)
    at emit (node:internal/child_process:938:14)
    at processTicksAndRejections (node:internal/process/task_queues:84:21) {
  errno: -4091,
  code: 'EADDRINUSE',
  syscall: 'bind',
  address: null,
  port: 8080
}
[2023-02-01T11:31:53.015] [ERROR] myLoggerError - Catch de error en servidor! Error: bind EADDRINUSE null:8080
    at listenOnPrimaryHandle (node:net:1397:18)
    at shared (node:internal/cluster/child:149:3)
    at Worker.<anonymous> (node:internal/cluster/child:106:7)
    at process.onInternalMessage (node:internal/cluster/utils:49:5)
    at process.emit (node:events:532:35)
    at emit (node:internal/child_process:938:14)
    at processTicksAndRejections (node:internal/process/task_queues:84:21) {
  errno: -4091,
  code: 'EADDRINUSE',
  syscall: 'bind',
  address: null,
  port: 8080
}
[2023-02-01T11:31:53.073] [ERROR] myLoggerError - Catch de error en servidor! Error: bind EADDRINUSE null:8080
    at listenOnPrimaryHandle (node:net:1397:18)
    at shared (node:internal/cluster/child:149:3)
    at Worker.<anonymous> (node:internal/cluster/child:106:7)
    at process.onInternalMessage (node:internal/cluster/utils:49:5)
    at process.emit (node:events:532:35)
    at emit (node:internal/child_process:938:14)
    at processTicksAndRejections (node:internal/process/task_queues:84:21) {
  errno: -4091,
  code: 'EADDRINUSE',
  syscall: 'bind',
  address: null,
  port: 8080
}
[2023-02-01T11:31:53.078] [ERROR] myLoggerError - Catch de error en servidor! Error: bind EADDRINUSE null:8080
    at listenOnPrimaryHandle (node:net:1397:18)
    at shared (node:internal/cluster/child:149:3)
    at Worker.<anonymous> (node:internal/cluster/child:106:7)
    at process.onInternalMessage (node:internal/cluster/utils:49:5)
    at process.emit (node:events:532:35)
    at emit (node:internal/child_process:938:14)
    at processTicksAndRejections (node:internal/process/task_queues:84:21) {
  errno: -4091,
  code: 'EADDRINUSE',
  syscall: 'bind',
  address: null,
  port: 8080
}
[2023-02-01T11:31:53.095] [ERROR] myLoggerError - Catch de error en servidor! Error: bind EADDRINUSE null:8080
    at listenOnPrimaryHandle (node:net:1397:18)
    at shared (node:internal/cluster/child:149:3)
    at Worker.<anonymous> (node:internal/cluster/child:106:7)
    at process.onInternalMessage (node:internal/cluster/utils:49:5)
    at process.emit (node:events:532:35)
    at emit (node:internal/child_process:938:14)
    at processTicksAndRejections (node:internal/process/task_queues:84:21) {
  errno: -4091,
  code: 'EADDRINUSE',
  syscall: 'bind',
  address: null,
  port: 8080
}
[2023-02-01T11:33:56.951] [ERROR] myLoggerError - PID MASTER= 19756
[2023-02-01T11:34:01.505] [ERROR] myLoggerError - Catch de error en servidor! Error: bind EADDRINUSE null:8080
    at listenOnPrimaryHandle (node:net:1397:18)
    at shared (node:internal/cluster/child:149:3)
    at Worker.<anonymous> (node:internal/cluster/child:106:7)
    at process.onInternalMessage (node:internal/cluster/utils:49:5)
    at process.emit (node:events:532:35)
    at emit (node:internal/child_process:938:14)
    at processTicksAndRejections (node:internal/process/task_queues:84:21) {
  errno: -4091,
  code: 'EADDRINUSE',
  syscall: 'bind',
  address: null,
  port: 8080
}
[2023-02-01T11:34:01.566] [ERROR] myLoggerError - Catch de error en servidor! Error: bind EADDRINUSE null:8080
    at listenOnPrimaryHandle (node:net:1397:18)
    at shared (node:internal/cluster/child:149:3)
    at Worker.<anonymous> (node:internal/cluster/child:106:7)
    at process.onInternalMessage (node:internal/cluster/utils:49:5)
    at process.emit (node:events:532:35)
    at emit (node:internal/child_process:938:14)
    at processTicksAndRejections (node:internal/process/task_queues:84:21) {
  errno: -4091,
  code: 'EADDRINUSE',
  syscall: 'bind',
  address: null,
  port: 8080
}
[2023-02-01T11:34:01.664] [ERROR] myLoggerError - Catch de error en servidor! Error: bind EADDRINUSE null:8080
    at listenOnPrimaryHandle (node:net:1397:18)
    at shared (node:internal/cluster/child:149:3)
    at Worker.<anonymous> (node:internal/cluster/child:106:7)
    at process.onInternalMessage (node:internal/cluster/utils:49:5)
    at process.emit (node:events:532:35)
    at emit (node:internal/child_process:938:14)
    at processTicksAndRejections (node:internal/process/task_queues:84:21) {
  errno: -4091,
  code: 'EADDRINUSE',
  syscall: 'bind',
  address: null,
  port: 8080
}
[2023-02-01T11:34:01.763] [ERROR] myLoggerError - Catch de error en servidor! Error: bind EADDRINUSE null:8080
    at listenOnPrimaryHandle (node:net:1397:18)
    at shared (node:internal/cluster/child:149:3)
    at Worker.<anonymous> (node:internal/cluster/child:106:7)
    at process.onInternalMessage (node:internal/cluster/utils:49:5)
    at process.emit (node:events:532:35)
    at emit (node:internal/child_process:938:14)
    at processTicksAndRejections (node:internal/process/task_queues:84:21) {
  errno: -4091,
  code: 'EADDRINUSE',
  syscall: 'bind',
  address: null,
  port: 8080
}
[2023-02-01T11:34:01.836] [ERROR] myLoggerError - Catch de error en servidor! Error: bind EADDRINUSE null:8080
    at listenOnPrimaryHandle (node:net:1397:18)
    at shared (node:internal/cluster/child:149:3)
    at Worker.<anonymous> (node:internal/cluster/child:106:7)
    at process.onInternalMessage (node:internal/cluster/utils:49:5)
    at process.emit (node:events:532:35)
    at emit (node:internal/child_process:938:14)
    at processTicksAndRejections (node:internal/process/task_queues:84:21) {
  errno: -4091,
  code: 'EADDRINUSE',
  syscall: 'bind',
  address: null,
  port: 8080
}
[2023-02-01T11:34:02.098] [ERROR] myLoggerError - Catch de error en servidor! Error: bind EADDRINUSE null:8080
    at listenOnPrimaryHandle (node:net:1397:18)
    at shared (node:internal/cluster/child:149:3)
    at Worker.<anonymous> (node:internal/cluster/child:106:7)
    at process.onInternalMessage (node:internal/cluster/utils:49:5)
    at process.emit (node:events:532:35)
    at emit (node:internal/child_process:938:14)
    at processTicksAndRejections (node:internal/process/task_queues:84:21) {
  errno: -4091,
  code: 'EADDRINUSE',
  syscall: 'bind',
  address: null,
  port: 8080
}
[2023-02-01T11:34:02.192] [ERROR] myLoggerError - Catch de error en servidor! Error: bind EADDRINUSE null:8080
    at listenOnPrimaryHandle (node:net:1397:18)
    at shared (node:internal/cluster/child:149:3)
    at Worker.<anonymous> (node:internal/cluster/child:106:7)
    at process.onInternalMessage (node:internal/cluster/utils:49:5)
    at process.emit (node:events:532:35)
    at emit (node:internal/child_process:938:14)
    at processTicksAndRejections (node:internal/process/task_queues:84:21) {
  errno: -4091,
  code: 'EADDRINUSE',
  syscall: 'bind',
  address: null,
  port: 8080
}
[2023-02-01T11:34:07.335] [ERROR] myLoggerError - Catch de error en servidor! Error: bind EADDRINUSE null:8080
    at listenOnPrimaryHandle (node:net:1397:18)
    at shared (node:internal/cluster/child:149:3)
    at Worker.<anonymous> (node:internal/cluster/child:106:7)
    at process.onInternalMessage (node:internal/cluster/utils:49:5)
    at process.emit (node:events:532:35)
    at emit (node:internal/child_process:938:14)
    at processTicksAndRejections (node:internal/process/task_queues:84:21) {
  errno: -4091,
  code: 'EADDRINUSE',
  syscall: 'bind',
  address: null,
  port: 8080
}
[2023-02-01T11:34:07.337] [ERROR] myLoggerError - Catch de error en servidor! Error: bind EADDRINUSE null:8080
    at listenOnPrimaryHandle (node:net:1397:18)
    at shared (node:internal/cluster/child:149:3)
    at Worker.<anonymous> (node:internal/cluster/child:106:7)
    at process.onInternalMessage (node:internal/cluster/utils:49:5)
    at process.emit (node:events:532:35)
    at emit (node:internal/child_process:938:14)
    at processTicksAndRejections (node:internal/process/task_queues:84:21) {
  errno: -4091,
  code: 'EADDRINUSE',
  syscall: 'bind',
  address: null,
  port: 8080
}
[2023-02-01T11:34:07.340] [ERROR] myLoggerError - Catch de error en servidor! Error: bind EADDRINUSE null:8080
    at listenOnPrimaryHandle (node:net:1397:18)
    at shared (node:internal/cluster/child:149:3)
    at Worker.<anonymous> (node:internal/cluster/child:106:7)
    at process.onInternalMessage (node:internal/cluster/utils:49:5)
    at process.emit (node:events:532:35)
    at emit (node:internal/child_process:938:14)
    at processTicksAndRejections (node:internal/process/task_queues:84:21) {
  errno: -4091,
  code: 'EADDRINUSE',
  syscall: 'bind',
  address: null,
  port: 8080
}
[2023-02-01T11:34:07.386] [ERROR] myLoggerError - Catch de error en servidor! Error: bind EADDRINUSE null:8080
    at listenOnPrimaryHandle (node:net:1397:18)
    at shared (node:internal/cluster/child:149:3)
    at Worker.<anonymous> (node:internal/cluster/child:106:7)
    at process.onInternalMessage (node:internal/cluster/utils:49:5)
    at process.emit (node:events:532:35)
    at emit (node:internal/child_process:938:14)
    at processTicksAndRejections (node:internal/process/task_queues:84:21) {
  errno: -4091,
  code: 'EADDRINUSE',
  syscall: 'bind',
  address: null,
  port: 8080
}
[2023-02-01T11:34:07.586] [ERROR] myLoggerError - Catch de error en servidor! Error: bind EADDRINUSE null:8080
    at listenOnPrimaryHandle (node:net:1397:18)
    at shared (node:internal/cluster/child:149:3)
    at Worker.<anonymous> (node:internal/cluster/child:106:7)
    at process.onInternalMessage (node:internal/cluster/utils:49:5)
    at process.emit (node:events:532:35)
    at emit (node:internal/child_process:938:14)
    at processTicksAndRejections (node:internal/process/task_queues:84:21) {
  errno: -4091,
  code: 'EADDRINUSE',
  syscall: 'bind',
  address: null,
  port: 8080
}
[2023-02-01T11:34:08.086] [ERROR] myLoggerError - Catch de error en servidor! Error: bind EADDRINUSE null:8080
    at listenOnPrimaryHandle (node:net:1397:18)
    at shared (node:internal/cluster/child:149:3)
    at Worker.<anonymous> (node:internal/cluster/child:106:7)
    at process.onInternalMessage (node:internal/cluster/utils:49:5)
    at process.emit (node:events:532:35)
    at emit (node:internal/child_process:938:14)
    at processTicksAndRejections (node:internal/process/task_queues:84:21) {
  errno: -4091,
  code: 'EADDRINUSE',
  syscall: 'bind',
  address: null,
  port: 8080
}
[2023-02-01T11:34:13.385] [ERROR] myLoggerError - Catch de error en servidor! Error: bind EADDRINUSE null:8080
    at listenOnPrimaryHandle (node:net:1397:18)
    at shared (node:internal/cluster/child:149:3)
    at Worker.<anonymous> (node:internal/cluster/child:106:7)
    at process.onInternalMessage (node:internal/cluster/utils:49:5)
    at process.emit (node:events:532:35)
    at emit (node:internal/child_process:938:14)
    at processTicksAndRejections (node:internal/process/task_queues:84:21) {
  errno: -4091,
  code: 'EADDRINUSE',
  syscall: 'bind',
  address: null,
  port: 8080
}
[2023-02-01T11:34:13.462] [ERROR] myLoggerError - Catch de error en servidor! Error: bind EADDRINUSE null:8080
    at listenOnPrimaryHandle (node:net:1397:18)
    at shared (node:internal/cluster/child:149:3)
    at Worker.<anonymous> (node:internal/cluster/child:106:7)
    at process.onInternalMessage (node:internal/cluster/utils:49:5)
    at process.emit (node:events:532:35)
    at emit (node:internal/child_process:938:14)
    at processTicksAndRejections (node:internal/process/task_queues:84:21) {
  errno: -4091,
  code: 'EADDRINUSE',
  syscall: 'bind',
  address: null,
  port: 8080
}
[2023-02-01T11:34:13.575] [ERROR] myLoggerError - Catch de error en servidor! Error: bind EADDRINUSE null:8080
    at listenOnPrimaryHandle (node:net:1397:18)
    at shared (node:internal/cluster/child:149:3)
    at Worker.<anonymous> (node:internal/cluster/child:106:7)
    at process.onInternalMessage (node:internal/cluster/utils:49:5)
    at process.emit (node:events:532:35)
    at emit (node:internal/child_process:938:14)
    at processTicksAndRejections (node:internal/process/task_queues:84:21) {
  errno: -4091,
  code: 'EADDRINUSE',
  syscall: 'bind',
  address: null,
  port: 8080
}
[2023-02-01T11:34:13.597] [ERROR] myLoggerError - Catch de error en servidor! Error: bind EADDRINUSE null:8080
    at listenOnPrimaryHandle (node:net:1397:18)
    at shared (node:internal/cluster/child:149:3)
    at Worker.<anonymous> (node:internal/cluster/child:106:7)
    at process.onInternalMessage (node:internal/cluster/utils:49:5)
    at process.emit (node:events:532:35)
    at emit (node:internal/child_process:938:14)
    at processTicksAndRejections (node:internal/process/task_queues:84:21) {
  errno: -4091,
  code: 'EADDRINUSE',
  syscall: 'bind',
  address: null,
  port: 8080
}
[2023-02-01T11:34:17.309] [ERROR] myLoggerError - Catch de error en servidor! Error: bind EADDRINUSE null:8080
    at listenOnPrimaryHandle (node:net:1397:18)
    at shared (node:internal/cluster/child:149:3)
    at Worker.<anonymous> (node:internal/cluster/child:106:7)
    at process.onInternalMessage (node:internal/cluster/utils:49:5)
    at process.emit (node:events:532:35)
    at emit (node:internal/child_process:938:14)
    at processTicksAndRejections (node:internal/process/task_queues:84:21) {
  errno: -4091,
  code: 'EADDRINUSE',
  syscall: 'bind',
  address: null,
  port: 8080
}
[2023-02-01T11:34:17.311] [ERROR] myLoggerError - Catch de error en servidor! Error: bind EADDRINUSE null:8080
    at listenOnPrimaryHandle (node:net:1397:18)
    at shared (node:internal/cluster/child:149:3)
    at Worker.<anonymous> (node:internal/cluster/child:106:7)
    at process.onInternalMessage (node:internal/cluster/utils:49:5)
    at process.emit (node:events:532:35)
    at emit (node:internal/child_process:938:14)
    at processTicksAndRejections (node:internal/process/task_queues:84:21) {
  errno: -4091,
  code: 'EADDRINUSE',
  syscall: 'bind',
  address: null,
  port: 8080
}
[2023-02-01T11:34:22.624] [ERROR] myLoggerError - Catch de error en servidor! Error: bind EADDRINUSE null:8080
    at listenOnPrimaryHandle (node:net:1397:18)
    at shared (node:internal/cluster/child:149:3)
    at Worker.<anonymous> (node:internal/cluster/child:106:7)
    at process.onInternalMessage (node:internal/cluster/utils:49:5)
    at process.emit (node:events:532:35)
    at emit (node:internal/child_process:938:14)
    at processTicksAndRejections (node:internal/process/task_queues:84:21) {
  errno: -4091,
  code: 'EADDRINUSE',
  syscall: 'bind',
  address: null,
  port: 8080
}
[2023-02-01T11:36:43.242] [ERROR] myLoggerError - PID MASTER= 26164
[2023-02-01T11:36:47.898] [ERROR] myLoggerError - Catch de error en servidor! Error: bind EADDRINUSE null:8080
    at listenOnPrimaryHandle (node:net:1397:18)
    at shared (node:internal/cluster/child:149:3)
    at Worker.<anonymous> (node:internal/cluster/child:106:7)
    at process.onInternalMessage (node:internal/cluster/utils:49:5)
    at process.emit (node:events:532:35)
    at emit (node:internal/child_process:938:14)
    at processTicksAndRejections (node:internal/process/task_queues:84:21) {
  errno: -4091,
  code: 'EADDRINUSE',
  syscall: 'bind',
  address: null,
  port: 8080
}
[2023-02-01T11:36:47.994] [ERROR] myLoggerError - Catch de error en servidor! Error: bind EADDRINUSE null:8080
    at listenOnPrimaryHandle (node:net:1397:18)
    at shared (node:internal/cluster/child:149:3)
    at Worker.<anonymous> (node:internal/cluster/child:106:7)
    at process.onInternalMessage (node:internal/cluster/utils:49:5)
    at process.emit (node:events:532:35)
    at emit (node:internal/child_process:938:14)
    at processTicksAndRejections (node:internal/process/task_queues:84:21) {
  errno: -4091,
  code: 'EADDRINUSE',
  syscall: 'bind',
  address: null,
  port: 8080
}
[2023-02-01T11:36:48.077] [ERROR] myLoggerError - Catch de error en servidor! Error: bind EADDRINUSE null:8080
    at listenOnPrimaryHandle (node:net:1397:18)
    at shared (node:internal/cluster/child:149:3)
    at Worker.<anonymous> (node:internal/cluster/child:106:7)
    at process.onInternalMessage (node:internal/cluster/utils:49:5)
    at process.emit (node:events:532:35)
    at emit (node:internal/child_process:938:14)
    at processTicksAndRejections (node:internal/process/task_queues:84:21) {
  errno: -4091,
  code: 'EADDRINUSE',
  syscall: 'bind',
  address: null,
  port: 8080
}
[2023-02-01T11:36:48.123] [ERROR] myLoggerError - Catch de error en servidor! Error: bind EADDRINUSE null:8080
    at listenOnPrimaryHandle (node:net:1397:18)
    at shared (node:internal/cluster/child:149:3)
    at Worker.<anonymous> (node:internal/cluster/child:106:7)
    at process.onInternalMessage (node:internal/cluster/utils:49:5)
    at process.emit (node:events:532:35)
    at emit (node:internal/child_process:938:14)
    at processTicksAndRejections (node:internal/process/task_queues:84:21) {
  errno: -4091,
  code: 'EADDRINUSE',
  syscall: 'bind',
  address: null,
  port: 8080
}
[2023-02-01T11:36:48.221] [ERROR] myLoggerError - Catch de error en servidor! Error: bind EADDRINUSE null:8080
    at listenOnPrimaryHandle (node:net:1397:18)
    at shared (node:internal/cluster/child:149:3)
    at Worker.<anonymous> (node:internal/cluster/child:106:7)
    at process.onInternalMessage (node:internal/cluster/utils:49:5)
    at process.emit (node:events:532:35)
    at emit (node:internal/child_process:938:14)
    at processTicksAndRejections (node:internal/process/task_queues:84:21) {
  errno: -4091,
  code: 'EADDRINUSE',
  syscall: 'bind',
  address: null,
  port: 8080
}
[2023-02-01T11:36:48.234] [ERROR] myLoggerError - Catch de error en servidor! Error: bind EADDRINUSE null:8080
    at listenOnPrimaryHandle (node:net:1397:18)
    at shared (node:internal/cluster/child:149:3)
    at Worker.<anonymous> (node:internal/cluster/child:106:7)
    at process.onInternalMessage (node:internal/cluster/utils:49:5)
    at process.emit (node:events:532:35)
    at emit (node:internal/child_process:938:14)
    at processTicksAndRejections (node:internal/process/task_queues:84:21) {
  errno: -4091,
  code: 'EADDRINUSE',
  syscall: 'bind',
  address: null,
  port: 8080
}
[2023-02-01T11:36:48.236] [ERROR] myLoggerError - Catch de error en servidor! Error: bind EADDRINUSE null:8080
    at listenOnPrimaryHandle (node:net:1397:18)
    at shared (node:internal/cluster/child:149:3)
    at Worker.<anonymous> (node:internal/cluster/child:106:7)
    at process.onInternalMessage (node:internal/cluster/utils:49:5)
    at process.emit (node:events:532:35)
    at emit (node:internal/child_process:938:14)
    at processTicksAndRejections (node:internal/process/task_queues:84:21) {
  errno: -4091,
  code: 'EADDRINUSE',
  syscall: 'bind',
  address: null,
  port: 8080
}
[2023-02-01T11:36:48.365] [ERROR] myLoggerError - Catch de error en servidor! Error: bind EADDRINUSE null:8080
    at listenOnPrimaryHandle (node:net:1397:18)
    at shared (node:internal/cluster/child:149:3)
    at Worker.<anonymous> (node:internal/cluster/child:106:7)
    at process.onInternalMessage (node:internal/cluster/utils:49:5)
    at process.emit (node:events:532:35)
    at emit (node:internal/child_process:938:14)
    at processTicksAndRejections (node:internal/process/task_queues:84:21) {
  errno: -4091,
  code: 'EADDRINUSE',
  syscall: 'bind',
  address: null,
  port: 8080
}
[2023-02-01T11:36:48.417] [ERROR] myLoggerError - Catch de error en servidor! Error: bind EADDRINUSE null:8080
    at listenOnPrimaryHandle (node:net:1397:18)
    at shared (node:internal/cluster/child:149:3)
    at Worker.<anonymous> (node:internal/cluster/child:106:7)
    at process.onInternalMessage (node:internal/cluster/utils:49:5)
    at process.emit (node:events:532:35)
    at emit (node:internal/child_process:938:14)
    at processTicksAndRejections (node:internal/process/task_queues:84:21) {
  errno: -4091,
  code: 'EADDRINUSE',
  syscall: 'bind',
  address: null,
  port: 8080
}
[2023-02-01T11:36:48.431] [ERROR] myLoggerError - Catch de error en servidor! Error: bind EADDRINUSE null:8080
    at listenOnPrimaryHandle (node:net:1397:18)
    at shared (node:internal/cluster/child:149:3)
    at Worker.<anonymous> (node:internal/cluster/child:106:7)
    at process.onInternalMessage (node:internal/cluster/utils:49:5)
    at process.emit (node:events:532:35)
    at emit (node:internal/child_process:938:14)
    at processTicksAndRejections (node:internal/process/task_queues:84:21) {
  errno: -4091,
  code: 'EADDRINUSE',
  syscall: 'bind',
  address: null,
  port: 8080
}
[2023-02-01T11:36:48.468] [ERROR] myLoggerError - Catch de error en servidor! Error: bind EADDRINUSE null:8080
    at listenOnPrimaryHandle (node:net:1397:18)
    at shared (node:internal/cluster/child:149:3)
    at Worker.<anonymous> (node:internal/cluster/child:106:7)
    at process.onInternalMessage (node:internal/cluster/utils:49:5)
    at process.emit (node:events:532:35)
    at emit (node:internal/child_process:938:14)
    at processTicksAndRejections (node:internal/process/task_queues:84:21) {
  errno: -4091,
  code: 'EADDRINUSE',
  syscall: 'bind',
  address: null,
  port: 8080
}
[2023-02-01T11:36:53.103] [ERROR] myLoggerError - Catch de error en servidor! Error: bind EADDRINUSE null:8080
    at listenOnPrimaryHandle (node:net:1397:18)
    at shared (node:internal/cluster/child:149:3)
    at Worker.<anonymous> (node:internal/cluster/child:106:7)
    at process.onInternalMessage (node:internal/cluster/utils:49:5)
    at process.emit (node:events:532:35)
    at emit (node:internal/child_process:938:14)
    at processTicksAndRejections (node:internal/process/task_queues:84:21) {
  errno: -4091,
  code: 'EADDRINUSE',
  syscall: 'bind',
  address: null,
  port: 8080
}
[2023-02-01T11:36:53.118] [ERROR] myLoggerError - Catch de error en servidor! Error: bind EADDRINUSE null:8080
    at listenOnPrimaryHandle (node:net:1397:18)
    at shared (node:internal/cluster/child:149:3)
    at Worker.<anonymous> (node:internal/cluster/child:106:7)
    at process.onInternalMessage (node:internal/cluster/utils:49:5)
    at process.emit (node:events:532:35)
    at emit (node:internal/child_process:938:14)
    at processTicksAndRejections (node:internal/process/task_queues:84:21) {
  errno: -4091,
  code: 'EADDRINUSE',
  syscall: 'bind',
  address: null,
  port: 8080
}
[2023-02-01T11:36:53.539] [ERROR] myLoggerError - Catch de error en servidor! Error: bind EADDRINUSE null:8080
    at listenOnPrimaryHandle (node:net:1397:18)
    at shared (node:internal/cluster/child:149:3)
    at Worker.<anonymous> (node:internal/cluster/child:106:7)
    at process.onInternalMessage (node:internal/cluster/utils:49:5)
    at process.emit (node:events:532:35)
    at emit (node:internal/child_process:938:14)
    at processTicksAndRejections (node:internal/process/task_queues:84:21) {
  errno: -4091,
  code: 'EADDRINUSE',
  syscall: 'bind',
  address: null,
  port: 8080
}
[2023-02-01T11:36:53.558] [ERROR] myLoggerError - Catch de error en servidor! Error: bind EADDRINUSE null:8080
    at listenOnPrimaryHandle (node:net:1397:18)
    at shared (node:internal/cluster/child:149:3)
    at Worker.<anonymous> (node:internal/cluster/child:106:7)
    at process.onInternalMessage (node:internal/cluster/utils:49:5)
    at process.emit (node:events:532:35)
    at emit (node:internal/child_process:938:14)
    at processTicksAndRejections (node:internal/process/task_queues:84:21) {
  errno: -4091,
  code: 'EADDRINUSE',
  syscall: 'bind',
  address: null,
  port: 8080
}
[2023-02-01T11:36:53.563] [ERROR] myLoggerError - Catch de error en servidor! Error: bind EADDRINUSE null:8080
    at listenOnPrimaryHandle (node:net:1397:18)
    at shared (node:internal/cluster/child:149:3)
    at Worker.<anonymous> (node:internal/cluster/child:106:7)
    at process.onInternalMessage (node:internal/cluster/utils:49:5)
    at process.emit (node:events:532:35)
    at emit (node:internal/child_process:938:14)
    at processTicksAndRejections (node:internal/process/task_queues:84:21) {
  errno: -4091,
  code: 'EADDRINUSE',
  syscall: 'bind',
  address: null,
  port: 8080
}
[2023-02-01T11:36:53.580] [ERROR] myLoggerError - Catch de error en servidor! Error: bind EADDRINUSE null:8080
    at listenOnPrimaryHandle (node:net:1397:18)
    at shared (node:internal/cluster/child:149:3)
    at Worker.<anonymous> (node:internal/cluster/child:106:7)
    at process.onInternalMessage (node:internal/cluster/utils:49:5)
    at process.emit (node:events:532:35)
    at emit (node:internal/child_process:938:14)
    at processTicksAndRejections (node:internal/process/task_queues:84:21) {
  errno: -4091,
  code: 'EADDRINUSE',
  syscall: 'bind',
  address: null,
  port: 8080
}
[2023-02-01T11:36:58.216] [ERROR] myLoggerError - Catch de error en servidor! Error: bind EADDRINUSE null:8080
    at listenOnPrimaryHandle (node:net:1397:18)
    at shared (node:internal/cluster/child:149:3)
    at Worker.<anonymous> (node:internal/cluster/child:106:7)
    at process.onInternalMessage (node:internal/cluster/utils:49:5)
    at process.emit (node:events:532:35)
    at emit (node:internal/child_process:938:14)
    at processTicksAndRejections (node:internal/process/task_queues:84:21) {
  errno: -4091,
  code: 'EADDRINUSE',
  syscall: 'bind',
  address: null,
  port: 8080
}
[2023-02-01T11:36:58.621] [ERROR] myLoggerError - Catch de error en servidor! Error: bind EADDRINUSE null:8080
    at listenOnPrimaryHandle (node:net:1397:18)
    at shared (node:internal/cluster/child:149:3)
    at Worker.<anonymous> (node:internal/cluster/child:106:7)
    at process.onInternalMessage (node:internal/cluster/utils:49:5)
    at process.emit (node:events:532:35)
    at emit (node:internal/child_process:938:14)
    at processTicksAndRejections (node:internal/process/task_queues:84:21) {
  errno: -4091,
  code: 'EADDRINUSE',
  syscall: 'bind',
  address: null,
  port: 8080
}
[2023-02-01T11:36:58.648] [ERROR] myLoggerError - Catch de error en servidor! Error: bind EADDRINUSE null:8080
    at listenOnPrimaryHandle (node:net:1397:18)
    at shared (node:internal/cluster/child:149:3)
    at Worker.<anonymous> (node:internal/cluster/child:106:7)
    at process.onInternalMessage (node:internal/cluster/utils:49:5)
    at process.emit (node:events:532:35)
    at emit (node:internal/child_process:938:14)
    at processTicksAndRejections (node:internal/process/task_queues:84:21) {
  errno: -4091,
  code: 'EADDRINUSE',
  syscall: 'bind',
  address: null,
  port: 8080
}
[2023-02-01T11:37:42.218] [ERROR] myLoggerError - PID MASTER= 6632
[2023-02-08T11:18:04.636] [ERROR] myLoggerError - Error: users validation failed: admin: Cast to Boolean failed for value "" (type string) at path "admin" because of "CastError", name: Path `name` is required., adress: Path `adress` is required., age: Path `age` is required., phone: Path `phone` is required., picture: Path `picture` is required.
    at ValidationError.inspect (D:\Pato\Coder House\Node Js\deployRailwayTercerEntrega\node_modules\mongoose\lib\error\validation.js:50:26)
    at formatValue (node:internal/util/inspect:780:19)
    at inspect (node:internal/util/inspect:345:10)
    at formatWithOptionsInternal (node:internal/util/inspect:2165:40)
    at Object.format (node:internal/util/inspect:2019:10)
    at basicLayout (D:\Pato\Coder House\Node Js\deployRailwayTercerEntrega\node_modules\log4js\lib\layouts.js:65:52)
    at app (D:\Pato\Coder House\Node Js\deployRailwayTercerEntrega\node_modules\log4js\lib\appenders\file.js:98:23)
    at D:\Pato\Coder House\Node Js\deployRailwayTercerEntrega\node_modules\log4js\lib\log4js.js:43:5
    at Array.forEach (<anonymous>)
    at sendLogEventToAppender (D:\Pato\Coder House\Node Js\deployRailwayTercerEntrega\node_modules\log4js\lib\log4js.js:42:21) {
  errors: {
    admin: CastError: Cast to Boolean failed for value "" (type string) at path "admin" because of "CastError"
        at SchemaBoolean.cast (D:\Pato\Coder House\Node Js\deployRailwayTercerEntrega\node_modules\mongoose\lib\schema\boolean.js:209:11)
        at SchemaBoolean.SchemaType.applySetters (D:\Pato\Coder House\Node Js\deployRailwayTercerEntrega\node_modules\mongoose\lib\schematype.js:1201:12)
        at model.$set (D:\Pato\Coder House\Node Js\deployRailwayTercerEntrega\node_modules\mongoose\lib\document.js:1421:22)
        at model.$set (D:\Pato\Coder House\Node Js\deployRailwayTercerEntrega\node_modules\mongoose\lib\document.js:1146:16)
        at model.Document (D:\Pato\Coder House\Node Js\deployRailwayTercerEntrega\node_modules\mongoose\lib\document.js:166:12)
        at model.Model (D:\Pato\Coder House\Node Js\deployRailwayTercerEntrega\node_modules\mongoose\lib\model.js:121:12)
        at new model (D:\Pato\Coder House\Node Js\deployRailwayTercerEntrega\node_modules\mongoose\lib\model.js:5038:15)
        at Strategy.signup [as _verify] (file:///D:/Pato/Coder%20House/Node%20Js/deployRailwayTercerEntrega/src/services/auth.js:32:21)
        at processTicksAndRejections (node:internal/process/task_queues:96:5) {
      stringValue: '""',
      messageFormat: undefined,
      kind: 'Boolean',
      value: '',
      path: 'admin',
      reason: [CastError],
      valueType: 'string'
    },
    name: ValidatorError: Path `name` is required.
        at validate (D:\Pato\Coder House\Node Js\deployRailwayTercerEntrega\node_modules\mongoose\lib\schematype.js:1346:13)
        at SchemaString.SchemaType.doValidate (D:\Pato\Coder House\Node Js\deployRailwayTercerEntrega\node_modules\mongoose\lib\schematype.js:1330:7)
        at D:\Pato\Coder House\Node Js\deployRailwayTercerEntrega\node_modules\mongoose\lib\document.js:2903:18
        at processTicksAndRejections (node:internal/process/task_queues:78:11) {
      properties: [Object],
      kind: 'required',
      path: 'name',
      value: '',
      reason: undefined,
      [Symbol(mongoose:validatorError)]: true
    },
    adress: ValidatorError: Path `adress` is required.
        at validate (D:\Pato\Coder House\Node Js\deployRailwayTercerEntrega\node_modules\mongoose\lib\schematype.js:1346:13)
        at SchemaString.SchemaType.doValidate (D:\Pato\Coder House\Node Js\deployRailwayTercerEntrega\node_modules\mongoose\lib\schematype.js:1330:7)
        at D:\Pato\Coder House\Node Js\deployRailwayTercerEntrega\node_modules\mongoose\lib\document.js:2903:18
        at processTicksAndRejections (node:internal/process/task_queues:78:11) {
      properties: [Object],
      kind: 'required',
      path: 'adress',
      value: '',
      reason: undefined,
      [Symbol(mongoose:validatorError)]: true
    },
    age: ValidatorError: Path `age` is required.
        at validate (D:\Pato\Coder House\Node Js\deployRailwayTercerEntrega\node_modules\mongoose\lib\schematype.js:1346:13)
        at SchemaString.SchemaType.doValidate (D:\Pato\Coder House\Node Js\deployRailwayTercerEntrega\node_modules\mongoose\lib\schematype.js:1330:7)
        at D:\Pato\Coder House\Node Js\deployRailwayTercerEntrega\node_modules\mongoose\lib\document.js:2903:18
        at processTicksAndRejections (node:internal/process/task_queues:78:11) {
      properties: [Object],
      kind: 'required',
      path: 'age',
      value: '',
      reason: undefined,
      [Symbol(mongoose:validatorError)]: true
    },
    phone: ValidatorError: Path `phone` is required.
        at validate (D:\Pato\Coder House\Node Js\deployRailwayTercerEntrega\node_modules\mongoose\lib\schematype.js:1346:13)
        at SchemaString.SchemaType.doValidate (D:\Pato\Coder House\Node Js\deployRailwayTercerEntrega\node_modules\mongoose\lib\schematype.js:1330:7)
        at D:\Pato\Coder House\Node Js\deployRailwayTercerEntrega\node_modules\mongoose\lib\document.js:2903:18
        at processTicksAndRejections (node:internal/process/task_queues:78:11) {
      properties: [Object],
      kind: 'required',
      path: 'phone',
      value: '',
      reason: undefined,
      [Symbol(mongoose:validatorError)]: true
    },
    picture: ValidatorError: Path `picture` is required.
        at validate (D:\Pato\Coder House\Node Js\deployRailwayTercerEntrega\node_modules\mongoose\lib\schematype.js:1346:13)
        at SchemaString.SchemaType.doValidate (D:\Pato\Coder House\Node Js\deployRailwayTercerEntrega\node_modules\mongoose\lib\schematype.js:1330:7)
        at D:\Pato\Coder House\Node Js\deployRailwayTercerEntrega\node_modules\mongoose\lib\document.js:2903:18
        at processTicksAndRejections (node:internal/process/task_queues:78:11) {
      properties: [Object],
      kind: 'required',
      path: 'picture',
      value: '',
      reason: undefined,
      [Symbol(mongoose:validatorError)]: true
    }
  },
  _message: 'users validation failed'
}
